# Generated by Django 2.2.2 on 2019-06-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD_&_DRINK', 'Food & Drink'), ('ENTERTAINMENT', 'Entertainment')], default='Food & Drink', max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Salary')], default='Salary', max_length=100),
        ),
    ]
