# Generated by Django 2.2.2 on 2019-06-15 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgety', '0003_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='user',
            new_name='owner',
        ),
    ]
